// OpenAI, Copyright LifeEXE. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "ToolsTypes.h"
#include "CommonTypes.generated.h"

UENUM(BlueprintType)
enum class EMessageContentType : uint8
{
    Text,
    Image_URL
};

USTRUCT(BlueprintType)
struct FImageURL
{
    GENERATED_BODY()
    /**
      Either a URL of the image or the base64 encoded image data.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString URL;

    /**
      Specifies the detail level of the image.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Detail{"auto"};
};

USTRUCT(BlueprintType)
struct FMessageContent
{
    GENERATED_BODY()

    /**
      The text content.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Text;

    /**
      The image content.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FImageURL Image_URL;

    /**
      The type of the content part.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Type{"text"};
};

USTRUCT(BlueprintType)
struct FMessage
{
    GENERATED_BODY()

    /**
      The role of the messages author. One of system, user, assistant, or tool.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Role;

    /**
      The contents of the message.
      content is required for all messages, and may be null for assistant messages with function calls.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Content;

    /**
      An array of content parts with a defined type,
      each can be of type text or image_url when passing in images.
      You can pass multiple images by adding multiple image_url content parts.
      Image input is only supported when using the gpt-4-visual-preview model.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    TArray<FMessageContent> ContentArray;

    /**
      The tool calls generated by the model, such as function calls.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    TArray<FToolCalls> Tool_Calls;

    /**
      Tool call that this message is responding to.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Tool_Call_ID;

    /**
      An optional name for the participant.
      Provides the model information to differentiate between participants of the same role.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Name;
};

USTRUCT(BlueprintType)
struct FOpenAIEvent
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Object;

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Created_At{};

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Level;

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Message;
};

USTRUCT(BlueprintType)
struct FOpenAIAuth
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    FString APIKey{};

    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    FString OrganizationID{};

    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    FString ProjectID{};

    bool IsEmpty() const { return APIKey.IsEmpty() || OrganizationID.IsEmpty() || ProjectID.IsEmpty(); }
};

USTRUCT(BlueprintType)
struct FOpenAIError
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString RawContent{};

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    bool WasError{false};
};

/*
    @todo: add more errors https://platform.openai.com/docs/guides/error-codes
*/
UENUM(BlueprintType)
enum class EOpenAIResponseError : uint8
{
    InvalidAPIKey = 0,
    NetworkError,
    ModelNotFound,
    InsufficientQuota,
    InvalidLanguageFormat,
    Unknown
};

// what is that? (=
USTRUCT(BlueprintType)
struct FHyperparams
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Batch_Size{};

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    float Learning_Rate_Multiplier{};

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 N_Epochs{};

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    float Prompt_Loss_Weight{};
};

USTRUCT(BlueprintType)
struct FUsage
{
    GENERATED_BODY()

    /**
      Number of tokens in the generated completion.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Completion_Tokens{};

    /**
      Number of tokens in the prompt.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Prompt_Tokens{};

    /**
      Total number of tokens used in the request (prompt + completion).
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Total_Tokens{};
};

UENUM(BlueprintType)
enum class ERole : uint8
{
    System,
    User,
    Assistant,
    Function,
    Tool
};

UENUM(BlueprintType)
enum class EOpenAIFinishReason : uint8
{
    Stop = 0,
    Length,
    Content_Filter,
    Tool_Calls,
    Null
};

namespace OpenAI
{
using ServiceSecrets = TArray<TTuple<FString, FString>>;
using QueryPairs = TArray<TTuple<FString, FString>>;

}  // namespace OpenAI
