// OpenAI, Copyright LifeEXE. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Provider/OpenAIOptional.h"
#include "ImageTypes.generated.h"

UENUM(BlueprintType)
enum class EImageModelEnum : uint8
{
    GPT_Image_1,
    GPT_Image_1_Mini,
    GPT_Image_1_5,
    ChatGPT_Image_Latest
};

UENUM(BlueprintType)
enum class EImageSizeGptImage1 : uint8
{
    Auto,
    Size_1024x1024,
    Size_1536x1024,
    Size_1024x1536
};

UENUM(BlueprintType)
enum class EOpenAIImageQuality : uint8
{
    Auto,
    High,
    Medium,
    Low
};

UENUM(BlueprintType)
enum class EOpenAIImageFormat : uint8
{
    URL,
    B64_JSON
};

UENUM(BlueprintType)
enum class EOpenAIImageBackground : uint8
{
    Auto,
    Transparent,
    Opaque
};

UENUM(BlueprintType)
enum class EOpenAIImageModeration : uint8
{
    Auto,
    Low
};

UENUM(BlueprintType)
enum class EOpenAIImageOutputFormat : uint8
{
    Png,
    Jpeg,
    Webp
};

///////////////////////////////////////////////////////
//                 REQUEST TYPES
///////////////////////////////////////////////////////

USTRUCT(BlueprintType)
struct FOpenAIImage
{
    GENERATED_BODY()

    /**
      A text description of the desired image(s).
      The maximum length is 32000 characters for the GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Prompt;

    /**
      Allows to set transparency for the background of the generated image(s).
      This parameter is only supported for gpt-image-1.
      Must be one of transparent, opaque or auto (default value).
      When auto is used, the model will automatically determine the best background for the image.
      If transparent, the output format needs to support transparency, so it should be set to either png (default value) or webp.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Background;

    /**
      The model to use for image generation. One of gpt-image-1, gpt-image-1-mini, gpt-image-1.5, or chatgpt-image-latest.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Model{"gpt-image-1"};

    /**
      Control the content-moderation level for images generated by gpt-image-1.
      Must be either low for less restrictive filtering or auto (default value).
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Moderation;

    /**
      The number of images to generate. Must be between 1 and 10.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    int32 N{1};

    /**
      The compression level (0-100%) for the generated images.
      This parameter is only supported for gpt-image-1 with the webp or jpeg output formats, and defaults to 100.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalInt Output_Compression{100};

    /**
      The format in which the generated images are returned.
      This parameter is only supported for gpt-image-1. Must be one of png, jpeg, or webp.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Output_Format{};

    /**
      The quality of the image that will be generated.

      auto (default value) will automatically select the best quality for the given model.
      high, medium and low are supported for the GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Quality{};

    /**
      The size of the generated images.
      Must be one of 1024x1024, 1536x1024 (landscape), 1024x1536 (portrait), or auto (default value) for the GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Size{"1024x1024"};

    /**
      The number of partial images to generate during streaming. Value must be between 0 and 3.
      This parameter is only supported for the GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalInt Partial_Images{};

    /**
      Generate the image in streaming mode. Defaults to false.
      This parameter is only supported for the GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalBool Stream{};

    /**
      A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString User;
};

USTRUCT(BlueprintType)
struct FOpenAIImageEdit
{
    GENERATED_BODY()

    /**
      The image(s) to edit. Must be a supported image file or an array of images.
      Each image should be a png, webp, or jpg file less than 25MB.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    TArray<FString> Image;

    /**
      A text description of the desired image(s).
      The maximum length is 32000 characters.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Prompt;

    /**
      Allows to set transparency for the background of the generated image(s).
      This parameter is only supported for gpt-image-1.
      Must be one of transparent, opaque or auto (default value).
      When auto is used, the model will automatically determine the best background for the image.
      If transparent, the output format needs to support transparency, so it should be set to either png (default value) or webp.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Background;

    /**
      Controls fidelity to the original input image(s). Must be one of high or low.
      This parameter is only supported for GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Input_Fidelity{};

    /**
      An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where image should be edited. If there are
      multiple images provided, the mask will be applied on the first image. Must be a valid PNG file, less than 4MB, and have the same
      dimensions as image.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Mask;

    /**
      The model to use for image editing.
      One of gpt-image-1.5, gpt-image-1, gpt-image-1-mini, or chatgpt-image-latest.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Model{"gpt-image-1"};

    /**
      Control the content-moderation level. Must be either low or auto (default value).
      Only supported for GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Moderation{};

    /**
      The number of images to generate. Must be between 1 and 10.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    int32 N{1};

    /**
      The compression level (0-100%) for the generated images.
      Only supported for GPT image models with webp or jpeg output formats.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalInt Output_Compression{};

    /**
      Output image format. Must be one of png, jpeg, or webp.
      Only supported for GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString Output_Format{};

    /**
      The number of partial images to generate during streaming. Value must be between 0 and 3.
      Only supported for GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalInt Partial_Images{};

    /**
      The quality of the image that will be generated.
      high, medium and low are supported for the GPT image models. Defaults to auto.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Quality{"auto"};

    /**
      The size of the generated images.
      Must be one of 1024x1024, 1536x1024 (landscape), 1024x1536 (portrait), or auto (default value).
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FString Size{"1024x1024"};

    /**
      Stream partial image results as events. Only supported for GPT image models.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalBool Stream{};

    /**
      A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    FOptionalString User;
};

///////////////////////////////////////////////////////
//                 RESPONSE TYPES
///////////////////////////////////////////////////////

/**
  Represents the url or the content of an image generated by the OpenAI API.
*/
USTRUCT(BlueprintType)
struct FImageObject
{
    GENERATED_BODY()

    /**
       The base64 - encoded JSON of the generated image, if response_format is b64_json.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString B64_JSON;

    /**
      The URL of the generated image, if response_format is url (default).
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString URL;

    /**
      The prompt that was used to generate the image, if there was any revision to the prompt.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Revised_Prompt;
};

USTRUCT(BlueprintType)
struct FInputTokensDetails
{
    GENERATED_BODY()
    /**
      The number of image tokens in the input prompt.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Image_Tokens{};

    /**
      The number of text tokens in the input prompt.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Text_Tokens{};
};

USTRUCT(BlueprintType)
struct FOutputTokensDetails
{
    GENERATED_BODY()

    /**
      The number of image output tokens generated by the model.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Image_Tokens{};

    /**
      The number of text output tokens generated by the model.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Text_Tokens{};
};

/**
  For gpt-image-1 only, the token usage information for the image generation.
*/
USTRUCT(BlueprintType)
struct FImageUsage
{
    GENERATED_BODY()

    /**
      The number of tokens (images and text) in the input prompt.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Input_Tokens{};

    /**
      The input tokens detailed information for the image generation.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FInputTokensDetails Input_Tokens_Details{};

    /**
      The number of image tokens in the output image.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Output_Tokens{};

    /**
      The total number of tokens (images and text) used for the image generation.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Total_Tokens{};

    /**
      The output token details for the image generation.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FOutputTokensDetails Output_Tokens_Details{};
};

USTRUCT(BlueprintType)
struct FImageResponse
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    int32 Created{};

    /**
      The background parameter used for the image generation. Either transparent or opaque.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Background;

    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    TArray<FImageObject> Data;

    /**
      The output format of the image generation. Either png, webp, or jpeg.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Output_Format;

    /**
      The quality of the image generated. Either low, medium, or high.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Quality;

    /**
      The size of the image generated.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FString Size;

    /**
      For gpt-image-1 only, the token usage information for the image generation.
    */
    UPROPERTY(BlueprintReadOnly, Category = "OpenAI")
    FImageUsage Usage;
};

USTRUCT(BlueprintType)
struct FImageEditResponse : public FImageResponse
{
    GENERATED_BODY()
};
