// OpenAI, Copyright LifeEXE. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "CommonTypes.generated.h"

USTRUCT(BlueprintType)
struct FFunctionCall
{
    GENERATED_BODY()

    /**
      The arguments to call the function with, as generated by the model in JSON format.
      Note that the model does not always generate valid JSON,
      and may hallucinate parameters not defined by your function schema.
      Validate the arguments in your code before calling your function.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Arguments;

    /**
        The name of the function to call.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Name;
};

USTRUCT(BlueprintType)
struct FMessage
{
    GENERATED_BODY()

    /**
        The role of the messages author. One of system, user, assistant, or function.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Role;

    /**
        The contents of the message.
        content is required for all messages, and may be null for assistant messages with function calls.
    */
    UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Required")
    FString Content;

    /**
        The name of the author of this message.
        name is required if role is function, and it should be the name of the function whose response is in the content.
        May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
    */
    // UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    // FString Name;

    /**
       The name and arguments of a function that should be called, as generated by the model.
   */
    //  UPROPERTY(BlueprintReadWrite, Category = "OpenAI | Optional")
    // FFunctionCall Function_Call;
};

USTRUCT(BlueprintType)
struct FOpenAIAuth
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    FString APIKey{};

    UPROPERTY(BlueprintReadWrite, Category = "OpenAI")
    FString OrganizationID{};

    bool IsEmpty() const { return APIKey.IsEmpty() || OrganizationID.IsEmpty(); }
};
